#!/bin/bash
# GitHub Pages Setup Commands
# Replace 'yourusername' with your actual GitHub username

echo "🚀 GitHub Pages Setup Instructions"
echo "=================================="
echo ""
echo "1. First, create a new repository on GitHub:"
echo "   - Go to github.com"
echo "   - Click '+' → 'New repository'"
echo "   - Name: pgi4-presentation"
echo "   - Make it Public"
echo "   - Don't initialize with README"
echo ""
echo "2. Then run these commands (replace 'yourusername'):"
echo ""
echo "git remote add origin https://github.com/janmarxen/pgi4-presentation.git"
echo "git push -u origin main"
echo ""
echo "3. Enable GitHub Pages:"
echo "   - Go to your repo on GitHub"
echo "   - Click 'Settings' tab"
echo "   - Scroll to 'Pages' section"
echo "   - Source: 'Deploy from a branch'"
echo "   - Branch: 'main' / '/ (root)'"
echo "   - Click 'Save'"
echo ""
echo "4. Your presentation will be available at:"
echo "   https://yourusername.github.io/pgi4-presentation/"
echo ""
echo "✅ Ready to share with interviewers!"
